web:
  build: .
  user: app
  volumes:
    - /data/ecs/storage-vault:/app/ecs-storage-vault
  env_file: .env
  links:
    - postgres
    - redis
    - postfix
    - sentry
    - memcached
  command: web

worker:
  build: .
  user: app
  volumes:
    - /data/ecs/storage-vault:/app/ecs-storage-vault
  env_file: .env
  links:
   - postgres
   - redis
   - postfix
   - memcached
  command: celery -A ecs.taskapp worker -l INFO

celerybeat:
  build: .
  user: app
  env_file: .env
  links:
    - postgres
    - redis
    - postfix
    - memcached
  command: celery -A ecs.taskapp beat -l INFO

nginx:
  build: ./compose/nginx
  # nginx does not do location bases client_cert_verify,
  # but client_cert_optional and export the client check result would be ok
  links:
    - web
    - sentry
  ports:
    - "0.0.0.0:80:80"
    - "443"

postgres:
  image: postgres:9.4
  volumes:
    - /data/ecs/postgres:/var/lib/postgresql/data
  env_file: .env

redis:
  image: redis:3.0

postfix:
  image: marvambass/versatile-postfix
  env_file: .env

mocca:
  build: ./compose/mocca
  links: nginx

pdfas:
  build: ./compose/pdfas
  links: nginx

memcache:
  image: memcached

sentry:
  image: slafs/sentry
  links:
    - postgres
    - redis
