
postgres:
  image: postgres:9.4
  volumes:
    - /data/ecs/postgres:/var/lib/postgresql/data
  env_file: .env

django:
  build: .
  user: django
  links:
    - postgres
    - redis
    - postfix
    - sentry
    - memcached
  command: /gunicorn.sh
  env_file: .env

nginx:
  build: ./compose/nginx
  # nginx does not do location bases client_cert_verify,
  # but client_cert_optional and export the client check result would be ok
  links:
    - django
    - sentry
  ports:
    - "0.0.0.0:80:80"
    - "443"

redis:
  image: redis:3.0

postfix:
  image: marvambass/versatile-postfix
  env_file: .env

mocca:
  build: ./compose/mocca
  links: nginx

pdfas:
  build: ./compose/pdfas
  links: nginx
  
memcache:
  image: memcached

sentry:
  image: slafs/sentry
  links:
    - postgres
    - redis

celeryworker:
  build: .
  user: django
  env_file: .env
  links:
   - postgres
   - redis
   - postfix
   - memcached
  command: celery -A ecs.taskapp worker -l INFO

celerybeat:
  build: .
  user: django
  env_file: .env
  links:
    - postgres
    - redis
    - postfix
    - memcached
  command: celery -A ecs.taskapp beat -l INFO
