global:
  smtp_from: prometheus@localhost
  smtp_smarthost: {{ salt['pillar.get']('docker:ip') }}:25

route:
  receiver: 'default'

receivers:
  - name: 'default'
    email_configs:
      - send_resolved: true
        to: root@localhost
