include:
  - common
  - docker
  - .directories
  - .extra
  - .ecs
  - .ssl
  - .nginx
  - .postfix
  - .stunnel
  - .postgresql
  - .storage
  - .scripts
  - .systemd
  - .backup {# depends on service-failed@.service from systemd #}
  - .update {# depends on service-failed@.service from systemd #}
  - .metric
  - .legacy
