#!/bin/bash

if ! $(gosu postgres psql ecs -qtc "\dt" | grep -q pghero_query_stats); then
    gosu postgres psql ecs -c 'CREATE TABLE "pghero_query_stats" ("id" serial primary key,
        "database" text, "user" text, "query" text, "query_hash" bigint,
        "total_time" float, "calls" bigint, "captured_at" timestamp);'
fi
if ! $(gosu postgres psql ecs -qtc "\di" | grep -q pghero_query_stats); then
    gosu postgres psql ecs -c 'CREATE INDEX ON "pghero_query_stats" ("database", "captured_at");'
fi
