version: 2

services:

  ecs.web:
    build:
      context: ecs
      args:
        - http_proxy
    user: app
    volumes:
      - /data/ecs-storage-vault:/app/ecs-storage-vault
    env_file:
      - .env
    ports:
      - "127.0.0.1:5000:5000"
    links:
      - redis
      - memcached
    command: web

  ecs.worker:
    build:
      context: ecs
      args:
        - http_proxy
    user: app
    volumes:
      - /data/ecs-storage-vault:/app/ecs-storage-vault
    env_file:
      - .env
    links:
      - redis
      - memcached
    command: worker

  ecs.beat:
    build:
      context: ecs
      args:
        - http_proxy
    user: app
    env_file:
      - .env
    links:
      - redis
      - memcached
    command: beat

  memcache:
    image: memcached
    expose:
      - ""

  redis:
    image: redis:3.0
    volumes:
      - /volatile/container/redis:

  mocca:
    build:
      context: mocca
      args:
        - http_proxy
    expose:
      - "8080"
    ports:
      - "127.0.0.1:5090:8080"

  pdfas:
    build:
      context: pdfas
      args:
        - http_proxy
    expose:
      - "8080"
    ports:
      - "127.0.0.1:5095:8080"

  cadvisor:
    image: google/cadvisor
    expose:
      - "8080"
    ports:
      - "127.0.0.1:5080:8080"
    command: ["", "--housekeeping_interval=4s"]

  {%- if pillar.get('ecs:prometheus:enabled') %}
  prometheus:
    image:
    links:
      - cadvisor
  {%- endif %}
