version: 2
services:
  nginx:
    build: ./compose/nginx
    # use nginx as reverse proxy
    # nginx does not do location based client_cert_verify,
    # but client_cert_optional and export the client check result would be ok
    ports:
      - "80:80"
      - "443:443"
    links:
      - ecs.web
      - mocca
      - pdfas
  {%- if pillar.get('ecs:sentry:enabled') %}
      - sentry
  {%- endif %}
  {%- if pillar.get('ecs:piwik:enabled') %}
      - piwik
  {%- endif %}
  {%- if pillar.get('ecs:prometheus:enabled') %}
      - prometheus
  {%- endif %}
